### ISSUE TITLE
modules: Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by ahdinosaur** [davidguttman/cssify#43]
after enabling css modules with 

```json
{
  "browserify": {
    "transform": [
      ["cssify", { "modules": true } ]
    ]
  }
}
```

i got this error caused by [this line](https://github.com/davidguttman/cssify/blob/master/lib/process-css.js#L54)

```
TypeError: Cannot read property 'debug' of undefined
    at processCss (/.../node_modules/cssify/lib/process-css.js:54:51)
    at DestroyableTransform._flush (/.../node_modules/cssify/lib/index.js:23:7)
    at DestroyableTransform.<anonymous> (/.../node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/.../node_modules/readable-stream/lib/_stream_writable.js:499:12)
    at finishMaybe (/.../node_modules/readable-stream/lib/_stream_writable.js:507:7)
    at endWritable (/.../node_modules/readable-stream/lib/_stream_writable.js:519:3)
    at DestroyableTransform.Writable.end (/.../node_modules/readable-stream/lib/_stream_writable.js:484:5)
```

a temporary hotfix is

```json
{
  "browserify": {
    "transform": [
      ["cssify", { "modules": true, "_flags": { "debug": true } } ]
    ]
  }
}
```

**Comment by faergeek** [comment]
Which version of browserify do you have?

**Comment by ahdinosaur** [comment]
as far as i can tell, was using `browserify@12.0.1` and `watchify@3.6.1`.

**Comment by faergeek** [comment]
Please test with PR I just submitted

**Comment by ahdinosaur** [comment]
yep, fixes the bug, thanks.

just wondering, is it supposed to set this `debug` to true when i call `browserify . -d -o bundle.js`? i can't tell reading `browserify` or `module-deps` source, but seems nothing additional is passed in if i `console.log(options)` in `cssify`.

**Comment by faergeek** [comment]
It's strange, but if you pass all options from CLI it works (`_flags` are there), if you use `package.json` it doesn't.

**Comment by ahdinosaur** [comment]
hmm, true. and from the [last line of the browserify transform docs](https://github.com/substack/node-browserify#btransformtr-opts):

> Options sent to the browserify constructor are also provided under opts._flags. These browserify options are sometimes required if your transform needs to do something different when browserify is run in debug mode, for example.

so maybe this is a bug.

**Comment by ahdinosaur** [comment]
[submitted an issue upstream](https://github.com/substack/node-browserify/issues/1463)

**Comment by faergeek** [comment]
Thanks, I wasn't sure that it is a documented behavior :+1:
